"""Value object-lər — kimliyi olmayan, dəyişməz, öz-özünü validasiya edən dəyərlər.

QAYDA: yararsız value object heç vaxt YARANA BİLMƏZ — validasiya konstruktordadır.
Bu, "yoxlamağı unutdum" sinfindən olan səhvləri tipin özü səviyyəsində bağlayır.
"""

from src.domain.value_objects.authorization import (
    ANTI_FRAUD_FORBIDDEN_ROLES,
    DUAL_CONTROL_APPROVAL_FLAG,
    AuthorizationError,
    HardlockLevel,
    PermissionEffect,
    PermissionFlag,
    RolePriority,
    SystemRole,
)
from src.domain.value_objects.credentials import (
    PIN_LENGTH,
    WEAK_PINS,
    EmailAddress,
    InvalidEmailError,
    InvalidPinError,
    Pin,
)
from src.domain.value_objects.identifiers import (
    AppealId,
    AttendanceRecordId,
    EmployeeId,
    ErpServerId,
    FineId,
    FineTypeId,
    LeaveRequestId,
    LeaveTypeId,
    OverrideId,
    PluginId,
    PositionId,
    SessionId,
    ShiftSwapRequestId,
    StoreId,
    TaskId,
    TenantId,
    WorkModeId,
)
from src.domain.value_objects.money import CURRENCY_CODE, InvalidMoneyError, Money
from src.domain.value_objects.penalty import (
    InvalidPenaltyInputError,
    LeavePenalty,
    calculate_leave_penalty,
)
from src.domain.value_objects.scheduling import (
    DEFAULT_TIMEZONE,
    InvalidScheduleError,
    LatenessAssessment,
    NaiveDatetimeError,
    TimeRange,
    assess_lateness,
    require_aware,
)

__all__ = [
    "ANTI_FRAUD_FORBIDDEN_ROLES",
    "CURRENCY_CODE",
    "DEFAULT_TIMEZONE",
    "DUAL_CONTROL_APPROVAL_FLAG",
    "PIN_LENGTH",
    "WEAK_PINS",
    "AppealId",
    "AttendanceRecordId",
    "AuthorizationError",
    "EmailAddress",
    "EmployeeId",
    "ErpServerId",
    "FineId",
    "FineTypeId",
    "HardlockLevel",
    "InvalidEmailError",
    "InvalidMoneyError",
    "InvalidPenaltyInputError",
    "InvalidPinError",
    "InvalidScheduleError",
    "LatenessAssessment",
    "LeavePenalty",
    "LeaveRequestId",
    "LeaveTypeId",
    "Money",
    "NaiveDatetimeError",
    "OverrideId",
    "PermissionEffect",
    "PermissionFlag",
    "Pin",
    "PluginId",
    "PositionId",
    "RolePriority",
    "SessionId",
    "ShiftSwapRequestId",
    "StoreId",
    "SystemRole",
    "TaskId",
    "TenantId",
    "TimeRange",
    "WorkModeId",
    "assess_lateness",
    "calculate_leave_penalty",
    "require_aware",
]
